"""Domain and Decision models for the VERITY AI Finance Controller Subsystem."""

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class ControllerRiskLevel(str, Enum):
    """Risk severity assigned by the Finance Controller policy engine."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    NONE = "NONE"


class ControllerActionType(str, Enum):
    """Categorized controller actions and recommendations."""
    REVIEW_CASE = "REVIEW_CASE"
    VERIFY_EVIDENCE = "VERIFY_EVIDENCE"
    VERIFY_ENTITY = "VERIFY_ENTITY"
    VERIFY_TRANSACTION = "VERIFY_TRANSACTION"
    INVESTIGATE_CONTRADICTION = "INVESTIGATE_CONTRADICTION"
    REQUEST_MISSING_EVIDENCE = "REQUEST_MISSING_EVIDENCE"
    CONFIRM_RECONCILIATION = "CONFIRM_RECONCILIATION"
    ESCALATE = "ESCALATE"
    NO_ACTION = "NO_ACTION"


class ControllerRecommendation(BaseModel):
    """A prioritized, actionable task generated by the Finance Controller for human operators."""
    action_type: ControllerActionType = Field(..., description="Classification of the required action")
    priority: int = Field(..., ge=1, le=10, description="Priority rank (1 is highest urgency)")
    title: str = Field(..., description="Concise human-readable action title")
    explanation: str = Field(..., description="Explanation of why this action is required")
    rationale: str = Field(..., description="Deterministic justification grounding this action")
    supporting_ids: List[str] = Field(
        default_factory=list,
        description="IDs of related evidence, claims, transactions, or discrepancies"
    )
    blocking_issue: bool = Field(default=False, description="Whether this issue blocks automated ledger posting")
    requires_human_action: bool = Field(default=True, description="Whether direct human intervention is required")


class ControllerDecision(BaseModel):
    """Overall controller verdict and decision intelligence on a financial case."""
    case_id: str = Field(..., description="Target financial case ID")
    risk_level: ControllerRiskLevel = Field(..., description="Evaluated controller risk level")
    decision: ControllerActionType = Field(..., description="Primary controller action/verdict")
    requires_human_review: bool = Field(..., description="Flag indicating if manual audit is mandatory")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Overall confidence score from deterministic pipeline")
    reasons: List[str] = Field(default_factory=list, description="Key deterministic reasons driving the decision")
    supporting_evidence_ids: List[str] = Field(default_factory=list, description="Referenced evidence item IDs")
    supporting_claim_ids: List[str] = Field(default_factory=list, description="Referenced claim IDs")
    supporting_transaction_ids: List[str] = Field(default_factory=list, description="Referenced transaction IDs")
    supporting_discrepancy_ids: List[str] = Field(default_factory=list, description="Referenced discrepancy IDs")
    recommended_actions: List[ControllerRecommendation] = Field(
        default_factory=list,
        description="Prioritized list of recommended operator steps"
    )
    uncertainty_reasons: List[str] = Field(default_factory=list, description="Factors contributing to uncertainty")
    deterministic_basis: Dict[str, Any] = Field(
        default_factory=dict,
        description="Summary of deterministic pipeline outputs serving as source of truth"
    )
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Diagnostic telemetry")


class ControllerBrief(BaseModel):
    """Executive controller brief synthesizing case state, financial accounting, and recommendations."""
    case_id: str = Field(..., description="Case identifier")
    executive_summary: str = Field(..., description="Clear natural-language summary for finance controllers")
    financial_summary: Dict[str, Any] = Field(default_factory=dict, description="Amounts, settled, and outstanding")
    risk_summary: str = Field(..., description="Summary of evaluated financial risks")
    unresolved_items: List[str] = Field(default_factory=list, description="Open discrepancies and pending questions")
    contradictions: List[Dict[str, Any]] = Field(default_factory=list, description="Detected financial contradictions")
    recommended_actions: List[ControllerRecommendation] = Field(default_factory=list, description="Prioritized actions")
    confidence_summary: str = Field(..., description="Explanation of confidence factors and deductions")
    evidence_summary: List[Dict[str, Any]] = Field(default_factory=list, description="Summary of ingested modalities")
    controller_decision: ControllerDecision = Field(..., description="Complete structured controller decision")


class ControllerExplainRequest(BaseModel):
    """User query payload for natural-language controller explainability."""
    question: Optional[str] = Field(default=None, description="Natural language question, e.g., 'Why is review required?'")
    detail_level: Optional[str] = Field(default="standard", description="'brief', 'standard', or 'detailed'")


class ControllerExplainResponse(BaseModel):
    """Response containing evidence-grounded explanation from the Controller intelligence layer."""
    case_id: str = Field(..., description="Target case ID")
    question: str = Field(..., description="The query answered")
    answer: str = Field(..., description="Evidence-grounded explanation")
    grounding_ids: List[str] = Field(default_factory=list, description="Traceable domain IDs cited in the answer")
    confidence: float = Field(..., description="Confidence score")
    fallback_used: bool = Field(default=False, description="Whether deterministic template fallback was utilized")


class ControllerAIResponse(BaseModel):
    """Schema for validating optional LLM generation against deterministic facts."""
    summary: str = Field(..., description="Executive summary generated by AI")
    key_findings: List[str] = Field(default_factory=list, description="Key facts identified")
    recommended_actions: List[str] = Field(default_factory=list, description="Actionable suggestions")
    uncertainty_notice: Optional[str] = Field(default=None, description="Identified risks and ambiguities")
