"""Generate Day 9 Financial Truth Reporting sample fixtures and cases."""

import json
from pathlib import Path


def create_day9_samples() -> None:
    samples_dir = Path("data/samples/day9")
    samples_dir.mkdir(parents=True, exist_ok=True)

    test_cases = [
        {
            "case_id": "DAY9-01-CONFIRMED",
            "description": "Exact invoice/payment/reference/entity match -> CONFIRMED",
            "claims": [{
                "id": "CLM-01",
                "evidence_id": "EVID-01",
                "claim_type": "INVOICE_ISSUED",
                "claimed_amount": 35000.0,
                "reference_id_hint": "408219381920",
                "counterparty_hint": "Rahul Kumar",
            }],
            "transactions": [{
                "id": "TXN-01",
                "amount": 35000.0,
                "direction": "CREDIT",
                "bank_reference": "408219381920",
                "origin_entity_id": "ENT-001",
                "evidence_ids": ["EVID-01-BANK"],
            }],
            "evidence": [
                {"id": "EVID-01", "modality": "INVOICE", "source_name": "inv_001.pdf", "source_type": "ZOHO_INVOICE", "raw_payload": "35k inv"},
                {"id": "EVID-01-BANK", "modality": "BANK_STATEMENT", "source_name": "bank.csv", "source_type": "BANK_CSV", "raw_payload": "35k credit"},
            ],
            "entities": [{
                "id": "ENT-001",
                "canonical_name": "Rahul Kumar",
                "entity_type": "INDIVIDUAL",
                "pan": "ABCDE1234F",
                "upi_ids": ["rahul@oksbi"],
                "phone_numbers": ["+919876543210"],
            }],
            "reconciliation_result": {
                "reconciliation_id": "REC-01",
                "status": "CONFIRMED",
                "expected_amount": 35000.0,
                "matched_amount": 35000.0,
                "outstanding_amount": 0.0,
                "confidence_score": 1.0,
                "supporting_signals": ["EXACT_REFERENCE", "EXACT_AMOUNT", "EXACT_ENTITY", "MATCHED_RELATIONSHIP"],
                "contradicting_signals": [],
                "explanation": "Full financial reconciliation was confirmed for Rahul Kumar.",
                "reason_codes": ["CONFIRMED"],
                "claim_ids": ["CLM-01"],
                "transaction_ids": ["TXN-01"],
                "evidence_ids": ["EVID-01", "EVID-01-BANK"],
                "entity_id": "ENT-001",
            },
            "expected_report_status": "CONFIRMED",
            "expected_confidence": 1.0,
            "expected_matched_amount": 35000.0,
            "expected_outstanding_amount": 0.0,
        },
        {
            "case_id": "DAY9-02-PARTIAL-SETTLEMENT",
            "description": "₹20,000 invoice with ₹15,000 partial payment -> PARTIALLY_SETTLED (Outstanding: ₹5,000)",
            "claims": [{
                "id": "CLM-02",
                "evidence_id": "EVID-02",
                "claim_type": "INVOICE_ISSUED",
                "claimed_amount": 20000.0,
                "counterparty_hint": "Priya Patel",
            }],
            "transactions": [{
                "id": "TXN-02",
                "amount": 15000.0,
                "direction": "CREDIT",
                "origin_entity_id": "ENT-002",
                "evidence_ids": ["EVID-02-BANK"],
            }],
            "evidence": [
                {"id": "EVID-02", "modality": "INVOICE", "source_name": "inv_002.pdf", "source_type": "ZOHO_INVOICE", "raw_payload": "20k inv"},
                {"id": "EVID-02-BANK", "modality": "BANK_STATEMENT", "source_name": "bank.csv", "source_type": "BANK_CSV", "raw_payload": "15k credit"},
            ],
            "entities": [{
                "id": "ENT-002",
                "canonical_name": "Priya Patel",
                "entity_type": "INDIVIDUAL",
            }],
            "reconciliation_result": {
                "reconciliation_id": "REC-02",
                "status": "PARTIALLY_SETTLED",
                "expected_amount": 20000.0,
                "matched_amount": 15000.0,
                "outstanding_amount": 5000.0,
                "confidence_score": 0.95,
                "supporting_signals": ["VALID_PARTIAL_PAYMENT", "EXACT_ENTITY"],
                "contradicting_signals": [],
                "explanation": "Valid partial payment recognized.",
                "reason_codes": ["PARTIALLY_SETTLED"],
                "claim_ids": ["CLM-02"],
                "transaction_ids": ["TXN-02"],
                "evidence_ids": ["EVID-02", "EVID-02-BANK"],
                "entity_id": "ENT-002",
            },
            "expected_report_status": "PARTIALLY_SETTLED",
            "expected_matched_amount": 15000.0,
            "expected_outstanding_amount": 5000.0,
        },
        {
            "case_id": "DAY9-03-CONTRADICTED-AMOUNT",
            "description": "₹20,000 claim vs ₹18,000 bank settlement -> CONTRADICTED",
            "claims": [{
                "id": "CLM-03",
                "evidence_id": "EVID-03",
                "claim_type": "INVOICE_ISSUED",
                "claimed_amount": 20000.0,
                "reference_id_hint": "408219381920",
            }],
            "transactions": [{
                "id": "TXN-03",
                "amount": 18000.0,
                "direction": "CREDIT",
                "bank_reference": "408219381920",
                "evidence_ids": ["EVID-03-BANK"],
            }],
            "evidence": [
                {"id": "EVID-03", "modality": "INVOICE", "source_name": "inv_003.pdf", "source_type": "ZOHO_INVOICE", "raw_payload": "20k inv"},
            ],
            "discrepancies": [{
                "id": "DISC-03",
                "discrepancy_type": "AMOUNT_MISMATCH",
                "severity": "ERROR",
                "message": "Amount mismatch: Claimed 20,000 vs Bank 18,000",
                "expected_value": "20000.00",
                "observed_value": "18000.00",
            }],
            "reconciliation_result": {
                "reconciliation_id": "REC-03",
                "status": "CONTRADICTED",
                "expected_amount": 20000.0,
                "matched_amount": 18000.0,
                "outstanding_amount": 20000.0,
                "confidence_score": 0.98,
                "supporting_signals": [],
                "contradicting_signals": ["AMOUNT_MISMATCH"],
                "explanation": "Contradiction detected.",
                "reason_codes": ["CONTRADICTED"],
                "claim_ids": ["CLM-03"],
                "transaction_ids": ["TXN-03"],
                "evidence_ids": ["EVID-03"],
            },
            "expected_report_status": "CONTRADICTED",
        },
        {
            "case_id": "DAY9-04-AMBIGUOUS-CANDIDATES",
            "description": "Two equally plausible ₹20,000 transactions -> AMBIGUOUS",
            "claims": [{
                "id": "CLM-04",
                "evidence_id": "EVID-04",
                "claim_type": "INVOICE_ISSUED",
                "claimed_amount": 20000.0,
            }],
            "transactions": [
                {"id": "TXN-04A", "amount": 20000.0, "direction": "CREDIT"},
                {"id": "TXN-04B", "amount": 20000.0, "direction": "CREDIT"},
            ],
            "reconciliation_result": {
                "reconciliation_id": "REC-04",
                "status": "AMBIGUOUS",
                "expected_amount": 20000.0,
                "matched_amount": 40000.0,
                "outstanding_amount": 0.0,
                "confidence_score": 0.60,
                "supporting_signals": ["AMBIGUOUS_CANDIDATES"],
                "contradicting_signals": [],
                "explanation": "Ambiguity preserved.",
                "reason_codes": ["AMBIGUOUS"],
                "claim_ids": ["CLM-04"],
                "transaction_ids": ["TXN-04A", "TXN-04B"],
            },
            "expected_report_status": "AMBIGUOUS",
            "expected_confidence": 0.60,
        },
        {
            "case_id": "DAY9-05-UNVERIFIABLE-NO-AMOUNT",
            "description": "'I sent the money' with no stated amount and no bank ledger -> UNVERIFIABLE",
            "claims": [{
                "id": "CLM-05",
                "evidence_id": "EVID-05",
                "claim_type": "PAYMENT_SENT",
                "claimed_amount": None,
            }],
            "transactions": [],
            "reconciliation_result": {
                "reconciliation_id": "REC-05",
                "status": "UNVERIFIABLE",
                "expected_amount": None,
                "matched_amount": 0.0,
                "outstanding_amount": 0.0,
                "confidence_score": 0.40,
                "supporting_signals": [],
                "contradicting_signals": [],
                "explanation": "Unverifiable claim.",
                "reason_codes": ["UNVERIFIABLE"],
                "claim_ids": ["CLM-05"],
            },
            "expected_report_status": "UNVERIFIABLE",
            "expected_confidence": 0.40,
        },
        {
            "case_id": "DAY9-06-UNMATCHED-TRANSACTION",
            "description": "Standalone bank credit of ₹35,000 -> UNMATCHED",
            "claims": [],
            "transactions": [{
                "id": "TXN-06",
                "amount": 35000.0,
                "direction": "CREDIT",
                "bank_reference": "408219381920",
            }],
            "reconciliation_result": {
                "reconciliation_id": "REC-06",
                "status": "UNMATCHED",
                "expected_amount": None,
                "matched_amount": 35000.0,
                "outstanding_amount": 0.0,
                "confidence_score": 1.0,
                "supporting_signals": [],
                "contradicting_signals": [],
                "explanation": "Unmatched ledger transaction.",
                "reason_codes": ["UNMATCHED"],
                "transaction_ids": ["TXN-06"],
            },
            "expected_report_status": "UNMATCHED",
            "expected_matched_amount": 35000.0,
        },
        {
            "case_id": "DAY9-07-CROSS-MODAL-CONFIRMED",
            "description": "Invoice + Bank CSV + WhatsApp + Screenshot -> CONFIRMED",
            "claims": [
                {"id": "CLM-07-INV", "evidence_id": "EVID-07-INV", "claim_type": "INVOICE_ISSUED", "claimed_amount": 50000.0, "reference_id_hint": "408219381920"},
                {"id": "CLM-07-CHAT", "evidence_id": "EVID-07-CHAT", "claim_type": "PAYMENT_SENT", "claimed_amount": 50000.0, "reference_id_hint": "408219381920"},
            ],
            "transactions": [{
                "id": "TXN-07",
                "amount": 50000.0,
                "direction": "CREDIT",
                "bank_reference": "408219381920",
                "evidence_ids": ["EVID-07-BANK"],
            }],
            "evidence": [
                {"id": "EVID-07-INV", "modality": "INVOICE", "source_name": "inv.pdf", "source_type": "ZOHO_INVOICE", "raw_payload": "50k inv"},
                {"id": "EVID-07-BANK", "modality": "BANK_STATEMENT", "source_name": "bank.csv", "source_type": "BANK_CSV", "raw_payload": "50k bank"},
                {"id": "EVID-07-CHAT", "modality": "MESSAGING_CHAT", "source_name": "chat.txt", "source_type": "WHATSAPP_EXPORT", "raw_payload": "50k sent"},
                {"id": "EVID-07-SS", "modality": "PAYMENT_SCREENSHOT", "source_name": "ss.png", "source_type": "MANUAL_UPLOAD", "raw_payload": "50k ss"},
            ],
            "reconciliation_result": {
                "reconciliation_id": "REC-07",
                "status": "CONFIRMED",
                "expected_amount": 50000.0,
                "matched_amount": 50000.0,
                "outstanding_amount": 0.0,
                "confidence_score": 1.0,
                "supporting_signals": ["EXACT_REFERENCE", "EXACT_AMOUNT", "MATCHED_RELATIONSHIP"],
                "contradicting_signals": [],
                "explanation": "Confirmed across 4 evidence sources.",
                "reason_codes": ["CONFIRMED"],
                "claim_ids": ["CLM-07-INV", "CLM-07-CHAT"],
                "transaction_ids": ["TXN-07"],
                "evidence_ids": ["EVID-07-INV", "EVID-07-BANK", "EVID-07-CHAT", "EVID-07-SS"],
            },
            "expected_report_status": "CONFIRMED",
            "expected_matched_amount": 50000.0,
        },
        {
            "case_id": "DAY9-08-MULTIPLE-CONTRADICTIONS",
            "description": "Amount mismatch + Entity mismatch in same case -> CONTRADICTED",
            "claims": [{
                "id": "CLM-08",
                "evidence_id": "EVID-08",
                "claim_type": "INVOICE_ISSUED",
                "claimed_amount": 30000.0,
                "counterparty_hint": "Rahul Kumar",
            }],
            "transactions": [{
                "id": "TXN-08",
                "amount": 25000.0,
                "direction": "CREDIT",
                "origin_entity_id": "ENT-ROHIT",
            }],
            "discrepancies": [
                {"id": "DISC-08A", "discrepancy_type": "AMOUNT_MISMATCH", "severity": "ERROR", "message": "Amount mismatch: 30k vs 25k"},
                {"id": "DISC-08B", "discrepancy_type": "ENTITY_MISMATCH", "severity": "CRITICAL", "message": "Entity mismatch: ENT-RAHUL vs ENT-ROHIT"},
            ],
            "reconciliation_result": {
                "reconciliation_id": "REC-08",
                "status": "CONTRADICTED",
                "expected_amount": 30000.0,
                "matched_amount": 25000.0,
                "outstanding_amount": 30000.0,
                "confidence_score": 0.98,
                "supporting_signals": [],
                "contradicting_signals": ["AMOUNT_MISMATCH", "ENTITY_MISMATCH"],
                "explanation": "Multiple contradictions detected.",
                "reason_codes": ["CONTRADICTED"],
                "claim_ids": ["CLM-08"],
                "transaction_ids": ["TXN-08"],
            },
            "expected_report_status": "CONTRADICTED",
        },
        {
            "case_id": "DAY9-09-MANY-TO-ONE-MILESTONES",
            "description": "Three milestone payments settling one invoice -> CONFIRMED",
            "claims": [{
                "id": "CLM-09",
                "evidence_id": "EVID-09",
                "claim_type": "INVOICE_ISSUED",
                "claimed_amount": 20000.0,
                "counterparty_hint": "Bharat Tech",
            }],
            "transactions": [
                {"id": "TXN-09A", "amount": 10000.0, "direction": "CREDIT", "origin_entity_id": "ENT-BHARAT"},
                {"id": "TXN-09B", "amount": 5000.0, "direction": "CREDIT", "origin_entity_id": "ENT-BHARAT"},
                {"id": "TXN-09C", "amount": 5000.0, "direction": "CREDIT", "origin_entity_id": "ENT-BHARAT"},
            ],
            "match_relationships": [{
                "id": "MAT-09",
                "relationship_type": "MANY_TO_ONE",
                "status": "MATCHED",
                "source_claim_ids": ["CLM-09"],
                "target_transaction_ids": ["TXN-09A", "TXN-09B", "TXN-09C"],
                "matched_amount": 20000.0,
                "target_amount": 20000.0,
                "score": 0.95,
                "matched_signals": ["SUM_AMOUNT_MATCH", "3_ITEMS_SUM"],
                "explanation": "Milestone sum match",
            }],
            "reconciliation_result": {
                "reconciliation_id": "REC-09",
                "status": "CONFIRMED",
                "expected_amount": 20000.0,
                "matched_amount": 20000.0,
                "outstanding_amount": 0.0,
                "confidence_score": 0.95,
                "supporting_signals": ["MANY_TO_ONE_SUM_MATCH", "EXACT_ENTITY"],
                "contradicting_signals": [],
                "explanation": "Milestone payments confirmed.",
                "reason_codes": ["CONFIRMED"],
                "claim_ids": ["CLM-09"],
                "transaction_ids": ["TXN-09A", "TXN-09B", "TXN-09C"],
            },
            "expected_report_status": "CONFIRMED",
            "expected_matched_amount": 20000.0,
        },
        {
            "case_id": "DAY9-10-ONE-TO-MANY-BULK",
            "description": "Bulk payment of ₹20,000 settling two invoices -> CONFIRMED",
            "claims": [
                {"id": "CLM-10A", "evidence_id": "EVID-10A", "claim_type": "INVOICE_ISSUED", "claimed_amount": 10000.0},
                {"id": "CLM-10B", "evidence_id": "EVID-10B", "claim_type": "INVOICE_ISSUED", "claimed_amount": 10000.0},
            ],
            "transactions": [{
                "id": "TXN-10-BULK",
                "amount": 20000.0,
                "direction": "CREDIT",
                "origin_entity_id": "ENT-SHREE",
            }],
            "match_relationships": [{
                "id": "MAT-10",
                "relationship_type": "ONE_TO_MANY",
                "status": "MATCHED",
                "source_claim_ids": ["CLM-10A", "CLM-10B"],
                "target_transaction_ids": ["TXN-10-BULK"],
                "matched_amount": 20000.0,
                "target_amount": 20000.0,
                "score": 0.95,
                "matched_signals": ["SUM_AMOUNT_MATCH"],
                "explanation": "Bulk payment match",
            }],
            "reconciliation_result": {
                "reconciliation_id": "REC-10",
                "status": "CONFIRMED",
                "expected_amount": 20000.0,
                "matched_amount": 20000.0,
                "outstanding_amount": 0.0,
                "confidence_score": 0.95,
                "supporting_signals": ["ONE_TO_MANY_SUM_MATCH", "EXACT_ENTITY"],
                "contradicting_signals": [],
                "explanation": "Bulk payment confirmed.",
                "reason_codes": ["CONFIRMED"],
                "claim_ids": ["CLM-10A", "CLM-10B"],
                "transaction_ids": ["TXN-10-BULK"],
            },
            "expected_report_status": "CONFIRMED",
            "expected_matched_amount": 20000.0,
        },
    ]

    output_file = samples_dir / "reporting_cases.json"
    with open(output_file, "w", encoding="utf-8") as f:
        json.dump({"test_cases": test_cases}, f, indent=2, ensure_ascii=False)

    print(f"Day 9 reporting cases generated at {output_file}")


if __name__ == "__main__":
    create_day9_samples()
